# Generated by Django 5.2.12 on 2026-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в кошику', 'verbose_name_plural': 'Товари в кошиках'},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_stock__gte', 0)), name='product_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount__isnull', True), models.Q(('discount__gte', 0), ('discount__lte', 100)), _connector='OR'), name='product_discount_0_100'),
        ),
    ]
